'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Razor_Crypter.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die namespace %1%
        '''{
        '''    class %2%
        '''    {
        '''    }
        '''}
        ''' ähnelt.
        '''</summary>
        Friend ReadOnly Property _String() As String
            Get
                Return ResourceManager.GetString("_String", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die public interface %1%
        '''{
        '''    string %5% { get; set; }
        '''    string %6% { get; set; }
        '''    string %7% { get; set; }
        '''    string %8% { get; set; }
        '''}
        '''public static class %10%
        '''{
        '''    private static %1% %3%;
        '''    public static void %4%(%1% %9%)
        '''    {
        '''        %3% = %9%;
        '''    }
        '''    public static string %5%
        '''    {
        '''        get { return %3%.%5%; }
        '''        set { %3%.%5% = value; }
        '''    }
        '''} ähnelt.
        '''</summary>
        Friend ReadOnly Property Application() As String
            Get
                Return ResourceManager.GetString("Application", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        '''</summary>
        Friend ReadOnly Property AVG() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("AVG", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &lt;project outputDir=&quot;%path%&quot; baseDir=&quot;%basedir%&quot; xmlns=&quot;http://confuser.codeplex.com&quot;&gt;
        '''  &lt;rule pattern=&quot;true&quot; preset=&quot;maximum&quot; /&gt;
        '''  &lt;module path=&quot;%stub%&quot;&gt;
        '''    &lt;rule pattern=&quot;true&quot; preset=&quot;maximum&quot; /&gt;
        '''  &lt;/module&gt;
        '''&lt;/project&gt; ähnelt.
        '''</summary>
        Friend ReadOnly Property config() As String
            Get
                Return ResourceManager.GetString("config", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        '''</summary>
        Friend ReadOnly Property ConfuserEx() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("ConfuserEx", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        '''</summary>
        Friend ReadOnly Property ESET() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("ESET", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die 	class %2%
        '''	{
        '''		public int %3%;
        '''		public String %4%; 
        '''		public String %9%;
        '''		public void %12%() {
        '''			String %8% = &quot;%7%&quot; + %9% + &quot;%5%&quot; + %4% + &quot;%6%&quot; + %3%;
        ''' 
        '''			System.Console.WriteLine (%8%);
        '''		}
        '''		public void %10%(String %9%){
        '''			this.%9% =  %9%;
        '''		}
        ''' 
        '''		public String %11%() {
        '''			return %9%;
        '''		}
        '''		struct %13%
        '''{
        '''            public int %14%;
        '''            public bool %15%;
        '''            public double %16%;
        '''   };
        '''}
        ''' ähnelt.
        '''</summary>
        Friend ReadOnly Property File() As String
            Get
                Return ResourceManager.GetString("File", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        '''</summary>
        Friend ReadOnly Property Google_Chrome() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Google_Chrome", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        '''</summary>
        Friend ReadOnly Property Microsoft_Corporation() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Microsoft_Corporation", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        '''</summary>
        Friend ReadOnly Property Mozilla() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Mozilla", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die using System;
        '''using System.IO;
        '''using System.IO.Compression;
        '''using Microsoft.VisualBasic;
        '''using System.Threading;
        '''using System.Reflection;
        '''using System.Runtime.CompilerServices;
        '''using System.Runtime.InteropServices;
        '''using System.Windows.Forms;
        '''using Microsoft.Win32;
        '''using System.Diagnostics;
        '''using System.Drawing;
        '''using System.Net;
        '''using System.Net.NetworkInformation;
        '''using System.Net.Sockets;
        '''using Microsoft.VisualBasic.CompilerServices;
        '''using System.Collections.Generic;
        '''[assembly: AssemblyT [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Friend ReadOnly Property Razor() As String
            Get
                Return ResourceManager.GetString("Razor", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
